version: '3.8'
services:
  tomcat:
    image: tomcat:10.1.11
    ports:
      - "8080:8080"
    volumes:
      - ./out/artifacts/innotech_hw1_war/innotech_hw1_war.war:/usr/local/tomcat/webapps/help-service.war
    restart: on-failure
